---
apiVersion: v1
kind: Service
metadata:
  name: shroomui-service
spec:
  selector:
    app: shroom-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
  type: NodePort