---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "shroomui.name" . }}-service
spec:
  selector:
    app: shroom-frontend
  ports:
  - protocol: TCP
    port: {{ .Values.shroomui.port }}
    targetPort: {{ .Values.shroomui.port }}
    nodePort: 30080
  type: NodePort